config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"

  as :user do
      get "/register", :to => "devise/registrations#new", as: :register 
      get "/login", :to => "devise/sessions#new", as: :login
      get "/account", :to => "devise/registrations#edit", as: :account
      get "/logout", :to => "devise/sessions#destroy", as: :logout
  end
    
  devise_for :users, skip: [:session]
    
  as :user do
      get "/login" => 'devise/sessions#new', as: :new_user_session
      post "/login" => 'devise/sessions#create', as: :user_session      
      delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
      
  resources :user_friendships

  resources :statuses
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'
    

  

end

app/models/status.rb
class Status < ActiveRecord::Base
    belongs_to :user
    
    validates :content, presence: true, 
                        length: {minimum:2}
    
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :profile_name, presence: true,
        uniqueness: true,
        format: {
            with: /\A[a-zA-Z0-9_-]*\z/,
            message:"Must be formatted correctly."
        }
    
    
    has_many :statuses
    has_many :user_friendships
    has_many :friends, through: :user_friendships
    
    def full_name
        first_name + " " + last_name
    end
    
    def to_param
        profile_name
    end
    
    def gravatar_url
        "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(email.downcase.strip)}?s=32"
    end
    
  end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
    belongs_to :user
    belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
 before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation) }
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
      @user = User.find_by_profile_name(params[:id])
      if @user
          @statuses = @user.statuses.all
          render action: :show
      else
        render file: 'public/404', status: 404, formats: [:html]
      end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)
    if params[:status].has_key?(:user_id)
        params[:status].delete(:user_id) 
    end
    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:user_id, :content)
    end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
  before_filter :authenticate_user!, only: [:new]

  def new
    if params[:friend_id]
      @friend = User.where(profile_name: params[:friend_id]).first
        
      @user_friendship = current_user.user_friendships.new(friend: @friend)
    else
      flash[:error] = "Friend required"
    end
  rescue ActiveRecord::RecordNotFound
    render file: 'public/404', status: :not_found
  end

  def create
    if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
      @friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
      @user_friendship = current_user.user_friendships.new(friend: @friend)
      if @user_friendship.save
        flash[:success] = "Friendship created."
      else
        flash[:error] = "There was a problem."
      end
      redirect_to profile_path(@friend)
    else
      flash[:error] = "Friend required"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def flash_class(type)
        case type
        when :alert
            "alert-danger"
        when :notice
            "alert-success"
        else 
            "alert-info"
        end
    end
    
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Treebook</a>
        </div>
        
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <% if user_signed_in? %>
                    <li><%= link_to current_user.full_name, account_path %></li>
                    <li><%= link_to "Sign out", logout_path %></li>
                <% else %>
                    <li><%= link_to "Sign Up", register_path %></li>
                    <li><%= link_to "Sign In", login_path %></li>
                <% end %>
            </ul>
        </div>
    </nav>
    
    <div class="container">
        <% flash.each do |type, message| %>
           <div class="alert <%= flash_class type %>">
                <button class="close" data-dismiss="alert">x</button>
                <%= message %>
            </div>
        <% end %>
       
     <%= yield %>
    </div>

        
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
    <h1><%= @user.full_name %></h1>
    <%= link_to "Add friend", new_user_friendship_path(friend_id: @user), class: 'btn btn-primary' %>
</div>

<% if @statuses %>
    <% @statuses.each do |status| %>
        <div class="well">
            <%= status.content %>
            <hr />
            <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago 
        </div>
    <% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :content %><br>
  </div>
  <div class="actions">
    <%= f.submit :post %>
  </div>
  
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<%= link_to "Post a new status", new_status_path, class: "btn btn-primary" %>
    
  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= link_to image_tag(status.user.gravatar_url), profile_path(status.user) %></td>
        <td><%= status.user.full_name %></td>
        <td><%= status.content %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/statuses_by_user.html.erb
<div class="page-header">
  <h1><%= @user.full_name %></h1>
</div>

<% @statuses.each do |status| %>
  <div class="well">
    <%= status.content %>
  </div>
<% end %>

app/views/user_friendships/new.html.erb
<% if flash[:error] %>
Not found.
<% else %>
<div class="page-header">
  <h1><%= @friend.full_name %></h1>
</div>

<p>
  Do you really want to friend <%= @friend.full_name %>?
</p>

    <%= form_for @user_friendship, method: :post do |form| %>
        <div class="form form-actions">
            <%= form.hidden_field :friend_id, value: @friend.profile_name %>
            <%= submit_tag "Yes, Add friend", class: 'btn btn-primary' %>
            <%= link_to "Cancel",profile_path(@friend), class: 'btn' %>
        </div>
    <% end %>

<% end %>

app/views/user_notifier/friend_request_accepted.html.erb
Hi! <%= @friend.first_name %>,

<%= @user.profile_name %> wants to be friends on Treebook. Isn't that great?

Love, Treebook.

app/views/user_notifier/friend_requested.html.erb
Hi! <%= @friend.first_name %>,

<%= @user.profile_name %> wants to be friends on Treebook. Isn't that great?

Love, Treebook.